definitions:
  Error:
    properties:
      code:
        type: integer
      message:
        type: string
    required:
    - code
    - message
    type: object
  Room:
    properties:
      id:
        type: string
      isPrivate:
        type: boolean
      ownerId:
        type: string
    required:
    - id
    - isPrivate
    - ownerId
    type: object
  User:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
    required:
    - email
    - id
    - name
    type: object
info:
  contact: {}
paths:
  /room/create:
    post:
      description: Create room
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Room'
        default:
          description: ""
          schema:
            $ref: '#/definitions/Error'
      security:
      - ApiKeyAuth: []
      summary: CreateRoom
      tags:
      - Room
  /user/create:
    post:
      description: Create user.
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/User'
        default:
          description: ""
          schema:
            $ref: '#/definitions/Error'
      security:
      - ApiKeyAuth: []
      summary: CreateUser
      tags:
      - User
  /user/me:
    get:
      description: Get  current authenticated user.
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/User'
        default:
          description: ""
          schema:
            $ref: '#/definitions/Error'
      security:
      - ApiKeyAuth: []
      summary: GetCurrentUser
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
