definitions:
  Chat:
    properties:
      history:
        items:
          $ref: '#/definitions/ChatMessage'
        type: array
      id:
        type: string
      roomId:
        type: string
    required:
    - history
    - id
    - roomId
    type: object
  ChatMessage:
    properties:
      isCurrentUser:
        type: boolean
      sentAt:
        type: string
      text:
        type: string
      user:
        $ref: '#/definitions/User'
    required:
    - isCurrentUser
    - sentAt
    - text
    - user
    type: object
  Error:
    properties:
      code:
        type: integer
      message:
        type: string
    required:
    - code
    - message
    type: object
  Room:
    properties:
      id:
        type: string
      isPrivate:
        type: boolean
      ownerId:
        type: string
    required:
    - id
    - isPrivate
    - ownerId
    type: object
  RoomDetail:
    properties:
      id:
        type: string
      isPrivate:
        type: boolean
      owner:
        $ref: '#/definitions/User'
      participants:
        items:
          $ref: '#/definitions/User'
        type: array
    required:
    - id
    - isPrivate
    - owner
    - participants
    type: object
  SendChatMessage:
    properties:
      text:
        example: hello world
        maxLength: 1500
        minLength: 1
        type: string
    required:
    - text
    type: object
  SendChatMessageResponse:
    properties:
      isOk:
        type: boolean
    required:
    - isOk
    type: object
  User:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
    required:
    - email
    - id
    - name
    type: object
info:
  contact: {}
paths:
  /room/{roomId}:
    get:
      description: Get detail of room
      parameters:
      - description: Room Id
        in: path
        name: roomId
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/RoomDetail'
        default:
          description: ""
          schema:
            $ref: '#/definitions/Error'
      security:
      - ApiKeyAuth: []
      summary: GetRoomDetail
      tags:
      - Room
  /room/{roomId}/chat:
    get:
      description: Get chat of room
      parameters:
      - description: Room Id
        in: path
        name: roomId
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Chat'
        default:
          description: ""
          schema:
            $ref: '#/definitions/Error'
      security:
      - ApiKeyAuth: []
      summary: GetChat
      tags:
      - Room
      - Chat
    post:
      description: Send message to a chat.
      parameters:
      - description: Room Id
        in: path
        name: roomId
        required: true
        type: string
      - description: Send chat message request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/SendChatMessage'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/SendChatMessageResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/Error'
      security:
      - ApiKeyAuth: []
      summary: SendChatMessage
      tags:
      - Room
      - Chat
  /room/create:
    post:
      description: Create room
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Room'
        default:
          description: ""
          schema:
            $ref: '#/definitions/Error'
      security:
      - ApiKeyAuth: []
      summary: CreateRoom
      tags:
      - Room
  /user/create:
    post:
      description: Create user.
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/User'
        default:
          description: ""
          schema:
            $ref: '#/definitions/Error'
      security:
      - ApiKeyAuth: []
      summary: CreateUser
      tags:
      - User
  /user/me:
    get:
      description: Get  current authenticated user.
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/User'
        default:
          description: ""
          schema:
            $ref: '#/definitions/Error'
      security:
      - ApiKeyAuth: []
      summary: GetCurrentUser
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
