definitions:
  Error:
    properties:
      code:
        type: integer
      message:
        type: string
    required:
    - code
    - message
    type: object
  User:
    properties:
      email:
        type: string
      name:
        type: string
      phone:
        type: string
    required:
    - email
    - name
    type: object
info:
  contact: {}
paths:
  /user/create:
    post:
      description: Create user.
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/User'
        default:
          description: ""
          schema:
            $ref: '#/definitions/Error'
      security:
      - ApiKeyAuth: []
      summary: CreateUser
      tags:
      - Auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
